### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by tivoa-gigatronik** [MicrosoftEdge/MicrosoftEdgeLauncher#12]
There is no license in this project at the moment.
Depending on this: https://help.github.com/articles/open-source-licensing/ it means that this code shall never be used, distributed and so on.
I _guess_, that it should be Apache 2 License like the rest of MS Edge: https://github.com/MicrosoftEdge/Status/blob/production/LICENSE.md

**Comment by andysterland** [comment]
Good catch! The repo should have an MIT license on it... Will update it asap.

**Comment by andysterland** [comment]
License now added, thanks for the report.
