### ISSUE TITLE
Prebuilt exe does not work

### ISSUE THREAD

**Issue by dcsoft4** [MicrosoftEdge/MicrosoftEdgeLauncher#3]
The prebuilt Release, `ProjectSpartanLauncher.exe`, does not work.  It seems outdated; for example, it does not contain the Usage statement that is displayed when no arguments are specified.  Nor does it perform the basic function.  It does not thing at all.  The latest code does work, though.  Just the prebuilt exe needs updating.

**Comment by andysterland** [comment]
Thanks, good catch, the exe was out of date (whoops). I just updated the exe and made a new [release]https://github.com/MicrosoftEdge/MicrosoftEdgeLauncher/releases/tag/1.0.0.0) that contains the latest code changes.

**Comment by dcsoft4** [comment]
Thank you Andy!
