### ISSUE TITLE
Major issue since last Windows/Edge update

### ISSUE THREAD

**Issue by jckleinbourg** [MicrosoftEdge/MicrosoftEdgeLauncher#6]
Since the last Microsoft Edge update (25.10586.0.0), using the launcher when Edge is already open launches a new blank Edge window instead of adding new tab with the url to the existing one

**Comment by jckleinbourg** [comment]
I found how to fix this bug (see pull request)
my fork is here: https://github.com/jckleinbourg/MicrosoftEdgeLauncher/releases/tag/1.0.9.0

**Comment by andysterland** [comment]
Thanks for the fix. I'll push out a new release on Monday.
